import time
import turtle

t1 = turtle.Turtle()
t2 = turtle.Turtle()
t2.hideturtle()
t3 = turtle.Turtle()
t3.hideturtle()
t4 = turtle.Turtle()
t4.hideturtle()
t1.speed(400)
t1.penup()
t1.goto(0, -120)
t1.pensize(6)
t1.color('pink')
t1.pendown()
t1.circle(120)
for i in range(12):
    t1.hideturtle()
    t1.penup()
    t1.goto(0, 0)
    t1.forward(90)
    t1.pendown()
    t1.forward(26)
    t1.right(30)
for _ in range(60):
    t1.pensize(2)
    t1.penup()
    t1.goto(0, 0)
    t1.forward(110)
    t1.pendown()
    t1.forward(10)
    t1.right(6)
sec = time.localtime().tm_sec
mnt = time.localtime().tm_min
hour = time.localtime().tm_hour
print(hour, mnt, sec)
t3.setheading(int(mnt) * (-6) + 90)
t4.setheading(int(sec) * (-6) + 90)
t2.setheading(int(hour) * (-30) + 90)
while True:
    t2.setheading(int(hour) * (-30) + 90)
    t2.color('blue')
    t2.pensize(4)
    t2.speed(300)
    t2.goto(0, 0)
    t2.clear()
    t2.forward(55)
    t2.showturtle()
    t2.right(0.3)
    t3.color('red')
    t3.pensize(3)
    t3.speed(300)
    t3.hideturtle()
    t3.goto(0, 0)
    t3.clear()
    t3.forward(70)
    t3.showturtle()
    t3.right(6)
    for j in range(60):
        t4.color('black')
        t4.pensize(2)
        t4.speed(300)
        t4.hideturtle()
        t4.goto(0, 0)
        t4.clear()
        t4.forward(85)
        t4.showturtle()
        t4.right(6)
        time.sleep(1)
