import time
import datetime
import turtle

turtle.tracer(0)

t2 = turtle.Turtle()
t2.hideturtle()
turtle.hideturtle()
turtle.penup()
turtle.goto(-195, 195)
turtle.pendown()
turtle.pensize(6)
turtle.color('black')
turtle.speed(100)
for i in range(4):
    turtle.forward(390)
    turtle.right(90)
turtle.pensize(4)
turtle.penup()
turtle.goto(-195, 65)
turtle.pendown()
turtle.forward(390)
turtle.penup()
turtle.goto(-195, -65)
turtle.pendown()
turtle.forward(390)
turtle.penup()
turtle.goto(-65, 195)
turtle.right(90)
turtle.pendown()
turtle.forward(390)
turtle.penup()
turtle.goto(65,195)
turtle.pendown()
turtle.forward(390)
turtle.pensize(2)
for j in range(160,-165,-32):
    turtle.penup()
    turtle.goto(j, 195)
    turtle.pendown()
    turtle.forward(390)
turtle.right(90)
for j in range(192, -192, -32):
    turtle.penup()
    turtle.goto(195, j)
    turtle.pendown()
    turtle.forward(390)
turtle.done()
